### ISSUE TITLE
[Feature Request]: get Matches by league

### ISSUE THREAD

**Issue by CodeModeYT** [bgrnwd/mobfot#16]
### What feature would you like to see?

I’d love to see a feature like
get_matches_by_league(id) (it could work just like get_matches_by_date(date))

**Comment by bgrnwd** [comment]
Hey @CodeModeYT , sorry it's taken a while to get back to you.

`get_matches_by_league` doesn't look to be an explicit endpoint on the API like `get_matches_by_date` is. I could return the [`matches` key](https://www.fotmob.com/api/leagues?id=47&tab=matches) from `get_league` though. (e.g. https://www.fotmob.com/leagues/47/matches/premier-league) Would that work for you?

**Comment by CodeModeYT** [comment]
> Hey @CodeModeYT , sorry it's taken a while to get back to you.
> 
> 
> 
> `get_matches_by_league` doesn't look to be an explicit endpoint on the API like `get_matches_by_date` is. I could return the [`matches` key](https://www.fotmob.com/api/leagues?id=47&tab=matches) from `get_league` though. (e.g. https://www.fotmob.com/leagues/47/matches/premier-league) Would that work for you?

That would also work, thank you so much!

**Comment by bgrnwd** [comment]
@CodeModeYT `1.4.0` has the new function in it. Let me know if it was what you were looking for

**Comment by CodeModeYT** [comment]
@bgrnwd Looks good so far; I'll try to implement it into my app asap and get back to you after I tested it. Thank you so much!

**Comment by CodeModeYT** [comment]
@bgrnwd Got to test it out today; it's perfect, thank you so much!
