### ISSUE TITLE
[Feature Request]: Add documentation about methods available and their parameters

### ISSUE THREAD

**Issue by bgrnwd** [bgrnwd/mobfot#9]
### What feature would you like to see?

This documentation could be auto generated or manually included in the README

**Comment by macccorehenni** [comment]
I agree with this sentiment.

**Comment by bgrnwd** [comment]
@macccorehenni Was able to tackle this today and documentation is now available here: https://bgrnwd.com/mobfot/

**Comment by bgrnwd** [comment]
Marking as done
